version: "3.8"

services:
  client-minecraft-server:
    container_name: worldql-client-server-node
    build:
      dockerfile: Docker/mammothClientServer.dockerfile
      context: .
    environment:
      WQL_CONTROL_PLANE_HOST: "control-plane"
      WQL_CONTROL_PLANE_HANDSHAKE_PORT: "5556"
      WQL_CONTROL_PLANE_PUSH_PORT: "5555"
      WQL_SELF_IDENT_HOST: "docker"
    links:
      - control-plane
    depends_on:
      - control-plane
    ports:
      - "25565:25565"
    networks:
      worldql:

  control-plane:
    container_name: worldql-mammoth-control-plane
    build:
      dockerfile: Docker/mammothControlPlane.dockerfile
      context: .
    environment:
      WQL_USER: ${WQL_USER}
      WQL_PASSWORD: ${WQL_PASSWORD}
      WQL_DB: ${WQL_DATABASE}
      WQL_HOST: "postgres-db" # Resolves to the postgres DB's internal IP
    links:
      - postgres-db
    depends_on:
      - postgres-db
    networks:
      worldql:

  postgres-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${WQL_USER}
      POSTGRES_PASSWORD: ${WQL_PASSWORD}
      POSTGRES_DB: ${WQL_DATABASE}
    restart: always
    networks:
      worldql:

# Uncomment this section to expose an adminer GUI to have a tool available for exploring the database
  debug-adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres-db"
    links:
      - postgres-db
    depends_on:
      - postgres-db
    networks:
      worldql:

networks:
  worldql:
