version: "3.8"

services:
  client-minecraft-server:
    container_name: worldql-client
    build:
      dockerfile: Docker/mammothClientServer.dockerfile
      context: .
    environment:
      WQL_POSTGRES_CONNECTION_STRING: "postgresql://docker:docker@postgres-db?port=5432&dbname=docker"
    links:
      - control-plane
      - postgres-db
    depends_on:
      - control-plane
      - postgres-db

  control-plane:
    container_name: worldql-mammoth
    build:
      dockerfile: Docker/mammothControlPlane.dockerfile
      context: .
    environment:
      WQL_POSTGRES_CONNECTION_STRING: "postgresql://docker:docker@postgres-db?port=5432&dbname=docker"
    links:
      - postgres-db
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "docker"
    restart: always

# Uncomment this section to expose an adminer GUI to have a tool available for exploring the database
  debug-adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres-db"
